require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - ./custom_cops/required_inverse_of_relations.rb

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 3
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  EnforcedStyle: template

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/ContextWording:
  Prefixes:
    - when
    - given

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 10

CustomCops/RequiredInverseOfRelations:
  Enabled: true
  Include:
    # Only Rails model files
    - !ruby/regexp /models\//
