require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 3
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true

Layout/LineLength:
  Max: 130
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  EnforcedStyle: template

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/ContextWording:
  Prefixes:
    - when
    - given

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 10
