name: Deploy Mock Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy mock server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: {{ "${{ secrets.FLY_API_TOKEN }}" }}
