---
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 4 %>
:queues:
  - [default, 1]
  - [mailers, 2]
  - [development_default, 1]
  - [development_mailers, 2]
  - [production_default, 1]
  - [production_mailers, 2]
