AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'

Lint/NonDeterministicRequireOrder:
  Exclude:
    - '../spec/rails_helper.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - '../template.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - '../template.rb'

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# TODO: Enable this rule later
Style/GlobalVars:
  Enabled: false

# TODO: Enable this rule later
Style/RegexpLiteral:
  Enabled: false

Style/TrivialAccessors:
  Exclude:
    - '../template.rb'
