source 'https://rubygems.org'

gem 'docker-api' # A lightweight Ruby client for the Docker Remote API
gem 'rspec' # BDD for Ruby
gem 'rspec-wait' # Wait for conditions in RSpec
gem 'rubocop', require: false # A Ruby static code analyzer and formatter, based on the community Ruby style guide.
gem 'serverspec' # RSpec tests for your servers
