# frozen_string_literal: true

# Allow Rails serve static file by default, this can be disable on Nginx addon
gsub_file('config/environments/production.rb', "ENV['RAILS_SERVE_STATIC_FILES'].present?", 'true')

insert_into_file 'config/environments/production.rb', after: /config.action_mailer.perform_caching.+\n/ do
  <<~RUBY.indent(2)

    config.action_mailer.asset_host = ENV.fetch('MAILER_DEFAULT_HOST', 'localhost')

    config.action_mailer.default_url_options = {
      host: ENV.fetch('MAILER_DEFAULT_HOST', 'localhost'),
      port: ENV.fetch('MAILER_DEFAULT_PORT', '3000')
    }
  RUBY
end

# Remove the incorrect fallback configuration (was generated by Rails)
# https://github.com/ruby-i18n/i18n/releases/tag/v1.1.0
gsub_file('config/environments/production.rb', 'config.i18n.fallbacks = true', '')

# Adding the correct fallback configuration along with default locale and available locales
environment do
  <<~RUBY
    # eg: AVAILABLE_LOCALES = 'en,th'
    config.i18n.available_locales = ENV.fetch('AVAILABLE_LOCALES', 'en').split(',')

    # eg: DEFAULT_LOCALE = 'en'
    config.i18n.default_locale = ENV.fetch('DEFAULT_LOCALE', 'en')

    # eg: FALLBACK_LOCALES = 'en,th'
    config.i18n.fallbacks = ENV.fetch('FALLBACK_LOCALES', 'en').split(',')

  RUBY
end
