# Remove the incorrect fallback configuration (was generated by Rails)
# https://github.com/ruby-i18n/i18n/releases/tag/v1.1.0
gsub_file('config/environments/production.rb', 'config.i18n.fallbacks = true', '')

# Adding the correct fallback configuration along with default locale and available locales
environment do
  <<~EOT
    config.i18n.available_locales = ENV.fetch('AVAILABLE_LOCALES').split(', ')
    config.i18n.default_locale = ENV.fetch('DEFAULT_LOCALE')
    config.i18n.fallbacks = ENV.fetch('FALLBACK_LOCALES').split(', ')
    
  EOT
end
